### ISSUE TITLE
HSV input

### ISSUE THREAD

**Issue by quintz** [hardillb/node-red-contrib-color-convert#10]
Hi,

I'm a bit stuck on the input side for a HSV object.

I pushing in an object with
msg.Hue
msg.Value
msg.Saturation

but I always get the error

"no output, normally means bad input"

Could you point where I'm wrong?

Thanks!

**Comment by hardillb** [comment]
From the README

> For the first 3 input modes the node will attempt to determine the input format of msg.payload from the 3 following:
> ...
>  a object with keys hue,saturation,lightness or value,brightness with values between 0-360 for hue and 0-100 for the others.

The input must be `msg.payload.hue`, `msg.payload.saturation` and `msg.payload.value`
