### ISSUE TITLE
HSV -> RGB returns wrong names for properties

### ISSUE THREAD

**Issue by WolfspiritM** [hardillb/node-red-contrib-color-convert#2]
Thanks for this converter!

I noticed that using HSV -> RGB with the following payload:
```json
{"hue":0,"saturation":100,"brightness":100}
```

Will result in a new payload that looks like this:
```json
{"hue":255,"saturation":0,"value":0}
```

But correct would be:
```json
{"red":255,"green":0,"blue":0}
```

You might want to add a check for rgb here:
https://github.com/hardillb/node-red-contrib-color-convert/blob/master/color.js#L108

(Same applies for HSL -> RGB aswell)

**Comment by RaymondMouthaan** [comment]
Noticed the same issue
