### ISSUE TITLE
CSS HEX option

### ISSUE THREAD

**Issue by bakman2** [hardillb/node-red-contrib-color-convert#4]
As not everything works with css names (read: only browsers do), is there a way to add a HEX option ?

conversion from RGB should be simple as:

`return '#' + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);`

**Comment by hardillb** [comment]
As I said on the Alexa node issue you raised, pull requests will be looked at favourably

**Comment by hardillb** [comment]
Sorry, thought this was linked to https://github.com/hardillb/node-red-alexa-home-skill-web/issues/84 but pull requests still welcome

**Comment by bakman2** [comment]
Pull request created, please verify.
