### ISSUE TITLE
Input not an array ...again

### ISSUE THREAD

**Issue by nob0dy80** [hardillb/node-red-contrib-color-convert#6]
since there was this problem onces again, i tried to optain that problem on mine. but that doesnt help.

i'm injecting the following rgb array:
 
![image](https://user-images.githubusercontent.com/28686079/65274701-42f26c00-db24-11e9-8ca7-2dba064eda2f.png)

but i get "Input not an array"

i'm pretty sure this is an array of 3 numbers, cause node-red debug says so.

Is this my mistake?

**Comment by hardillb** [comment]
From the doc:

> For the first 3 input modes the node will attempt to determine the input format of msg.payload from the 3 following

The input should be in `msg.payload` not `msg.rgb`

**Comment by nob0dy80** [comment]
you are very fast in closing issues. not everone is a programmer.
so i did a function between to fetch out the rgb and putting it into payload with

msg.payload =
{
data:
msg.rgb
};
return msg

debug shows the array again, now i get 
![image](https://user-images.githubusercontent.com/28686079/65275434-f871ef00-db25-11e9-9e99-c139e11a71c5.png)


would be really kind if you help me further

**Comment by hardillb** [comment]
Try again, what you have created is `msg.payload.data` not `msg.payload`

**Comment by nob0dy80** [comment]
could be so simple
msg.payload = msg.rgb
return msg

Now it works, thanks for your input mate.

**Comment by nob0dy80** [comment]
good work by the way.
