### ISSUE TITLE
Color conversion for HSL to RGB doesn't consider the brightness

### ISSUE THREAD

**Issue by geoffreydemaagd** [hardillb/node-red-contrib-color-convert#7]
When doing a conversion from HUE HSV values to RGB the node doesn't check the brightness.
The output of the RGB is thus not correct. RGB colors are not build the same way Hue lamps are build.

I think there should be a conversion of the HUE colors mixed with the brightness.
What I do is convert the HSV to HSL, than change the L with the brightness and then do a convert to RGB. 
Is it possible to add that feauture into the RGB conversion?

Many thanks

**Comment by hardillb** [comment]
Feel free to submit a pull request and I'll have a look

**Comment by geoffreydemaagd** [comment]
I'll close this issue and will try to make something. Now I do this with mulitiple of node to accomplish this
